version: '3.8'

services:
  db-migration:
    build:
      context: .
      dockerfile: Dockerfile.db.migration
    volumes:
      - app-data:/app-data

  rl-arena:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - DB_PATH=/app-data/app.db
    volumes:
      - app-data:/app-data
    depends_on:
      - db-migration
volumes:
  app-data:
