version: '3.8'

services:
  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - DB_PATH=/app-data/app.db
    volumes:
      - app-data:/app-data
    command: >
      sh -c "goose -dir=migrations sqlite3 /app-data/app.db up &&
             /backend"

volumes:
  app-data:
